fix: install unzip if not already present and update CloudFront cache invalidation path

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,6 +68,12 @@ jobs:
       - name: Install AWS CLI
         id: check-aws-cli
         run: |
+          # Install unzip if not already installed
+          if ! command -v unzip &> /dev/null; then
+            echo "unzip not found. Installing..."
+            sudo apt-get update && sudo apt-get install -y unzip
+          fi
+
           if ! command -v aws &> /dev/null; then
             echo "AWS CLI not found. Installing..."
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
@@ -91,4 +97,4 @@ jobs:
       # Invalidate CloudFront Cache (Optional)
       - name: Invalidate CloudFront Cache
         run: |
-          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
+          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/app/*"
